openapi: 3.1.0
info:
  title: Todo AI Chatbot API
  description: API for conversational todo management interface
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.todoapp.com
    description: Production server

paths:
  /api/{user_id}/chat:
    post:
      summary: Process chat message and return AI response
      description: Handles user chat messages, processes with AI agent, and returns response
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user making the request
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: The user's chat message
                  example: "Create a task to buy groceries tomorrow"
                conversation_id:
                  type: string
                  format: uuid
                  description: Optional conversation ID to continue existing conversation
                  example: "123e4567-e89b-12d3-a456-426614174000"
              required:
                - message
      responses:
        '200':
          description: Successful response from AI agent
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: The AI agent's response to the user
                    example: "I've created a task 'buy groceries' for tomorrow."
                  conversation_id:
                    type: string
                    format: uuid
                    description: The conversation ID for continuity
                    example: "123e4567-e89b-12d3-a456-426614174000"
                  tool_calls:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: The name of the tool that was called
                        arguments:
                          type: object
                          description: The arguments passed to the tool
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - invalid or missing JWT
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - user attempting to access another user's data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/{user_id}/conversations:
    get:
      summary: List user's conversations
      description: Retrieve a paginated list of user's conversations
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user making the request
          schema:
            type: string
            format: uuid
        - name: limit
          in: query
          description: Maximum number of conversations to return
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          description: Number of conversations to skip
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: List of user's conversations
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversations:
                    type: array
                    items:
                      $ref: '#/components/schemas/Conversation'
                  total:
                    type: integer
                    description: Total number of conversations
                  limit:
                    type: integer
                    description: Number of conversations returned
                  offset:
                    type: integer
                    description: Number of conversations skipped
        '401':
          description: Unauthorized - invalid or missing JWT
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - user attempting to access another user's data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/{user_id}/conversations/{conversation_id}:
    get:
      summary: Get conversation details
      description: Retrieve details and messages for a specific conversation
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user making the request
          schema:
            type: string
            format: uuid
        - name: conversation_id
          in: path
          required: true
          description: The ID of the conversation to retrieve
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Conversation details with messages
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationWithMessages'
        '401':
          description: Unauthorized - invalid or missing JWT
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - user attempting to access another user's data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Conversation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Conversation:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the conversation
        user_id:
          type: string
          format: uuid
          description: ID of the user who owns the conversation
        created_at:
          type: string
          format: date-time
          description: When the conversation was created
        updated_at:
          type: string
          format: date-time
          description: When the conversation was last updated
      required:
        - id
        - user_id
        - created_at
        - updated_at

    Message:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the message
        conversation_id:
          type: string
          format: uuid
          description: ID of the conversation this message belongs to
        user_id:
          type: string
          format: uuid
          description: ID of the user who sent the message
        role:
          type: string
          enum: [user, assistant]
          description: Whether this is a user or assistant message
        content:
          type: string
          description: The content of the message
        created_at:
          type: string
          format: date-time
          description: When the message was created
      required:
        - id
        - conversation_id
        - user_id
        - role
        - content
        - created_at

    ConversationWithMessages:
      type: object
      properties:
        conversation:
          $ref: '#/components/schemas/Conversation'
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
      required:
        - conversation
        - messages

    Error:
      type: object
      properties:
        error:
          type: string
          description: A description of the error
        code:
          type: string
          description: A code representing the error type
      required:
        - error
        - code

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []