"""Initial tables for users and tasks

Revision ID: 001
Revises:
Create Date: 2026-01-04 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import uuid
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Detect if we're using PostgreSQL or SQLite
    conn = op.get_bind()
    dialect_name = conn.dialect.name

    if dialect_name == 'postgresql':
        # PostgreSQL-specific setup
        op.execute("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";")

        # Create users table with PostgreSQL UUID
        op.create_table('users',
            sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
            sa.Column('email', sa.VARCHAR(length=255), nullable=False),
            sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('email')
        )

        # Create tasks table with PostgreSQL UUID
        op.create_table('tasks',
            sa.Column('id', sa.Integer, sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False), nullable=False),
            sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('title', sa.VARCHAR(length=200), nullable=False),
            sa.Column('description', sa.TEXT, nullable=True),
            sa.Column('completed', sa.Boolean, server_default=sa.text('false'), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )

        # Create triggers for updating updated_at (PostgreSQL)
        op.execute("""
            CREATE OR REPLACE FUNCTION update_updated_at_column()
            RETURNS TRIGGER AS $$
            BEGIN
                NEW.updated_at = NOW();
                RETURN NEW;
            END;
            $$ language 'plpgsql';
        """)

        op.execute("""
            CREATE TRIGGER update_users_updated_at
                BEFORE UPDATE ON users
                FOR EACH ROW
                EXECUTE FUNCTION update_updated_at_column();
        """)

        op.execute("""
            CREATE TRIGGER update_tasks_updated_at
                BEFORE UPDATE ON tasks
                FOR EACH ROW
                EXECUTE FUNCTION update_updated_at_column();
        """)

        # Create check constraints (PostgreSQL)
        op.execute("""
            ALTER TABLE users
            ADD CONSTRAINT email_format_check
            CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$');
        """)

        op.execute("""
            ALTER TABLE tasks
            ADD CONSTRAINT title_length_check
            CHECK (LENGTH(title) BETWEEN 1 AND 200);
        """)

        op.execute("""
            ALTER TABLE tasks
            ADD CONSTRAINT description_length_check
            CHECK (description IS NULL OR LENGTH(description) <= 1000);
        """)
    else:
        # SQLite-specific setup
        # Create users table with CHAR(36) for UUID storage
        op.create_table('users',
            sa.Column('id', sa.CHAR(length=36), nullable=False),  # For UUID as string
            sa.Column('email', sa.VARCHAR(length=255), nullable=False),
            sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
            sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('email')
        )

        # Create tasks table with CHAR(36) for user_id (to store UUID as string)
        op.create_table('tasks',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.CHAR(length=36), nullable=False),  # For UUID as string
            sa.Column('title', sa.VARCHAR(length=200), nullable=False),
            sa.Column('description', sa.TEXT(), nullable=True),
            sa.Column('completed', sa.Boolean(), server_default='0', nullable=False),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
            sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )

    # Create indexes (works for both databases)
    op.create_index('idx_users_email', 'users', ['email'])
    op.create_index('idx_tasks_user_id', 'tasks', ['user_id'])
    op.create_index('idx_tasks_completed', 'tasks', ['completed'])
    op.create_index('idx_tasks_user_created', 'tasks', ['user_id', 'created_at'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    dialect_name = conn.dialect.name

    # Drop indexes (works for both databases)
    op.drop_index('idx_tasks_user_created')
    op.drop_index('idx_tasks_completed')
    op.drop_index('idx_tasks_user_id')
    op.drop_index('idx_users_email')

    if dialect_name == 'postgresql':
        # PostgreSQL-specific cleanup
        op.execute("DROP TRIGGER IF EXISTS update_tasks_updated_at ON tasks;")
        op.execute("DROP TRIGGER IF EXISTS update_users_updated_at ON users;")
        op.execute("DROP FUNCTION IF EXISTS update_updated_at_column();")

        op.execute("ALTER TABLE tasks DROP CONSTRAINT IF EXISTS description_length_check;")
        op.execute("ALTER TABLE tasks DROP CONSTRAINT IF EXISTS title_length_check;")
        op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS email_format_check;")

    # Drop tables
    op.drop_table('tasks')
    op.drop_table('users')

    # We don't drop the uuid-ossp extension as it might be used by other databases
    # ### end Alembic commands ###